In [1]:
import pandas as pd
import numpy as np

In [2]:
df_32_pixels = pd.read_csv('./modeling_32p_results_df.csv' , sep= ';')
df_100_pixels = pd.read_csv('./modeling_100p_results_df.csv' , sep= ';')

In [3]:
df_32_pixels.head()

   train loss  train accuracy  val accuracy  test loss  test accuracy
0    0.297549        0.883000      0.835000   0.367514       0.855556
1    0.121091        0.955333      0.863333   0.449334       0.863333
2    0.067231        0.978667      0.855000   0.476706       0.862222
3    0.065393        0.976000      0.836667   0.587036       0.856667
4    0.040689        0.985000      0.850000   0.633120       0.871111

In [4]:
df_100_pixels.head()

   train loss  train accuracy  val accuracy  test loss  test accuracy
0    0.253640        0.895333      0.870000   0.346277       0.868889
1    0.118861        0.952000      0.880000   0.342630       0.882222
2    0.061287        0.976000      0.878333   0.343724       0.885556
3    0.070440        0.975000      0.870000   0.424380       0.876667
4    0.051324        0.983000      0.865000   0.482697       0.872222

In [5]:
print('32: ' , len(df_32_pixels.index))
print('100: ' , len(df_100_pixels.index))

32:  108
100:  42

Due to a writting error in the saving .csv code in the model params search notebook, the index needs to be extract manually.

In [6]:
index_100 = []

pool_sizes_1 = [(3,3) , (5,5)]
pool_sizes_2 = [(3,3) , (5,5)]
pool_sizes_3 = [(3,3) , (5,5)]

n_neurons = [400, 500, 600]

epochs = [20 , 30 , 40 , 50]
batchs = [32 , 64 , 128]



for pool_1 in pool_sizes_1:
    for pool_2 in pool_sizes_2:
        for pool_3 in pool_sizes_3:
            for n in n_neurons:
                for epoch in epochs:
                    for batch in batchs:
                        index_100.append((100 , pool_1 , pool_2 , pool_3 , n , epoch , batch))

index_100 = index_100[:42]

model_index = pd.MultiIndex.from_tuples(index_100)
df_100_pixels =  df_100_pixels.set_index(model_index)
df_100_pixels.head()

                                     train loss  train accuracy  val accuracy  \
100 (3, 3) (3, 3) (3, 3) 400 20 32     0.253640        0.895333      0.870000
                                64     0.118861        0.952000      0.880000
                                128    0.061287        0.976000      0.878333
                             30 32     0.070440        0.975000      0.870000
                                64     0.051324        0.983000      0.865000

                                     test loss  test accuracy
100 (3, 3) (3, 3) (3, 3) 400 20 32    0.346277       0.868889
                                64    0.342630       0.882222
                                128   0.343724       0.885556
                             30 32    0.424380       0.876667
                                64    0.482697       0.872222

In [7]:
df_100_pixels.tail()

                                     train loss  train accuracy  val accuracy  \
100 (3, 3) (3, 3) (5, 5) 400 20 64     0.170122        0.934000      0.868333
                                128    0.111154        0.956333      0.861667
                             30 32     0.120623        0.953000      0.876667
                                64     0.064219        0.976667      0.871667
                                128    0.034803        0.988000      0.883333

                                     test loss  test accuracy
100 (3, 3) (3, 3) (5, 5) 400 20 64    0.320279       0.882222
                                128   0.361258       0.890000
                             30 32    0.413095       0.878889
                                64    0.444246       0.880000
                                128   0.499488       0.883333

In [8]:
index_32 = []

pool_sizes_1 = [(2,2) , (3,3) , (4,4) , (5,5)]
pool_sizes_2 = [(2,2) , (3,3) , (4,4) , (5,5)]
pool_sizes_3 = [(2,2) , (3,3) , (4,4) , (5,5)]

n_neurons = [400, 500, 600]

epochs = [20 , 30 , 40 , 50]
batchs = [32 , 64 , 128]

for pool_1 in pool_sizes_1:
    for pool_2 in pool_sizes_2:
        for pool_3 in pool_sizes_3:
            for n in n_neurons:
                for epoch in epochs:
                    for batch in batchs:
                        index_32.append((32 , pool_1 , pool_2 , pool_3 , n , epoch , batch))

index_32 = index_32[:108]

model_index = pd.MultiIndex.from_tuples(index_32)
df_32_pixels =  df_32_pixels.set_index(model_index)
df_32_pixels.head()

                                    train loss  train accuracy  val accuracy  \
32 (2, 2) (2, 2) (2, 2) 400 20 32     0.297549        0.883000      0.835000
                               64     0.121091        0.955333      0.863333
                               128    0.067231        0.978667      0.855000
                            30 32     0.065393        0.976000      0.836667
                               64     0.040689        0.985000      0.850000

                                    test loss  test accuracy
32 (2, 2) (2, 2) (2, 2) 400 20 32    0.367514       0.855556
                               64    0.449334       0.863333
                               128   0.476706       0.862222
                            30 32    0.587036       0.856667
                               64    0.633120       0.871111

In [9]:
df_32_pixels.tail()

                                    train loss  train accuracy  val accuracy  \
32 (2, 2) (2, 2) (4, 4) 600 40 64     0.062537        0.978667      0.855000
                               128    0.021514        0.992667      0.856667
                            50 32     0.052100        0.982333      0.853333
                               64     0.031697        0.989333      0.853333
                               128    0.015817        0.995333      0.840000

                                    test loss  test accuracy
32 (2, 2) (2, 2) (4, 4) 600 40 64    0.583358       0.855556
                               128   0.642707       0.870000
                            50 32    0.715612       0.860000
                               64    0.618491       0.870000
                               128   0.760456       0.867778

In [10]:
print('Max test accuracy in 32 x 32 pixels')
max_32 = df_32_pixels[df_32_pixels['test accuracy'] == df_32_pixels['test accuracy'].max()]
display(max_32)
print('-----------------------------------------------------------------')
print('Max test accuracy in 100 x 100 pixels')
max_100 = df_100_pixels[df_100_pixels['test accuracy'] == df_100_pixels['test accuracy'].max()]
display(max_100)

Max test accuracy in 32 x 32 pixels

                                    train loss  train accuracy  val accuracy  \
32 (2, 2) (2, 2) (4, 4) 400 30 128    0.048675        0.983000      0.871667
                        500 30 128    0.058405        0.978333      0.865000

                                    test loss  test accuracy
32 (2, 2) (2, 2) (4, 4) 400 30 128   0.539551       0.885556
                        500 30 128   0.481576       0.885556

-----------------------------------------------------------------
Max test accuracy in 100 x 100 pixels

,,,,,,,train loss,train accuracy,val accuracy,test loss,test accuracy
100,"(3, 3)","(3, 3)","(3, 3)",400,50,128,0.009912,0.996667,0.885,0.583434,0.912222

The parameters selected for the prediction model are the following:

- Image shape (pixels) ==> 100 x 100
- Image format (color) ==> Full color (3 layers RGB)

- 1st convolutional layer (filters, strides) == (32 , (3,3)) ----- Constant during experiment
- 1st pooling layer (size) ==> (3,3)
- 2nd convolutional layer (filters, strides) == (64 , (3,3)) ----- Constant during experiment
- 2nd pooling layer (size) ==> (3,3)
- 3rd convolutional layer (filters, strides) == (128 , (3,3)) ----- Constant during experiment
- 3rd pooling layer (size) ==> (3,3)
- Activation functions (for all layers) ==> 'relu' ----- Constant during experiment
- Dropout (for all convolutional layers) ==> 0.25 ----- Constant during experiment

- Flatten layer
- 1st dense layer (n_neurons , activation , dropout) ==> 400 , 'relu' , 0.5
- Exit dense layer (n_neurons , activarion) ==> 3 , 'softmax'

- Compile parameters (optimizer , loss , metrics) ==> 'adam' , 'categorical_crossentropy' , 'accuracy' ----- Constant during experiment

- Training parameters (epochs, batch size) ==> 50 , 128

In [11]:
model_1 = [('32x32'),('2 x 2'),('2 x 2'),('4 x 4'),'400','30','128','0.048675','0.983000','0.871667','0.539551','0.885556']
model_2 = [('32x32'),('2 x 2'),('2 x 2'),('4 x 4'),'500','30','128','0.058405','0.978333','0.865000','0.481576','0.885556']
model_3 = [('100 x 100'),('3 x 3'),('3 x 3'),('3 x 3'),'400','50','128','0.009912','0.996667','0.885','0.583434','0.912222']

In [14]:
params_values = np.array([model_1 , model_2 , model_3])
params_names = ['Image size (pixels)' , '1st pooling layer (size)' , '2nd pooling layer (size)' , '3rd pooling layer(size)' , '1st dense layer neurons' , 'Epochs' , 'Batch size' , 'Train loss' , 'Train accuracy' ,	'Validation accuracy' , 'Test loss' , 'Test accuracy']
params_df = pd.DataFrame(params_values , columns= params_names)
params_df

,Image size (pixels),1st pooling layer (size),2nd pooling layer (size),3rd pooling layer(size),1st dense layer neurons,Epochs,Batch size,Train loss,Train accuracy,Validation accuracy,Test loss,Test accuracy
0,32x32,2 x 2,2 x 2,4 x 4,400,30,128,0.048675,0.983000,0.871667,0.539551,0.885556
1,32x32,2 x 2,2 x 2,4 x 4,500,30,128,0.058405,0.978333,0.865000,0.481576,0.885556
2,100 x 100,3 x 3,3 x 3,3 x 3,400,50,128,0.009912,0.996667,0.885,0.583434,0.912222

In [15]:
params_df.to_csv('../../cetaceous_group_predictor/best_models.csv' , sep= ';' , index=False)

In [17]:
constant_params_values = ['3' , '32' , '3 x 3' , '64' , '3 x 3' , '128' , '3 x 3' , 'relu' , '0.25' , 'Softmax']
constant_params_names = ['Image layers' , '1st conv layer filters' , '1st conv layer strides' , '2nd conv layer filters' , '2nd conv layer strides' ,'3rd conv layer filters' , '3rd conv layer strides',
'Conv layers activation function' , 'Conv dropout' , 'Exit layer activation']

constant_df = pd.DataFrame([constant_params_values] , columns=constant_params_names)
constant_df

,Image layers,1st conv layer filters,1st conv layer strides,2nd conv layer filters,2nd conv layer strides,3rd conv layer filters,3rd conv layer strides,Conv layers activation function,Conv dropout,Exit layer activation
0,3,32,3 x 3,64,3 x 3,128,3 x 3,relu,0.25,Softmax

In [18]:
training_cte_values = ['adam' , 'categorical_crossentropy' , 'accuracy']
training_cte_names = ['optimizer' , 'loss' , 'metric']
train_cte_df = pd.DataFrame([training_cte_values] , columns= training_cte_names)
train_cte_df

  optimizer                      loss    metric
0      adam  categorical_crossentropy  accuracy

In [19]:
constant_df.to_csv('../../cetaceous_group_predictor/model_ctes.csv' , sep= ';' , index=False)
train_cte_df.to_csv('../../cetaceous_group_predictor/train_ctes.csv' , sep= ';' , index=False)